apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-api-ingress-locally
  namespace: app-dev-arc
spec:
  podSelector:
    matchLabels:
      app: reviewer-api
  policyTypes:
    - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
      podSelector:
        matchLabels:
          app: traefik
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-ui-egress-all
  namespace: app-dev-arc
spec:
  podSelector:
    matchLabels:
      app: reviewer-ui
  policyTypes:
    - Egress
